### PR TITLE
Update readme with a description on how to build

### PR DESCRIPTION
**Pull request by petter-fidesmo**
- Add instructions on where to get SBT
- Add instructions on how to set up lolca.properties to point to SDK

### CODE REVIEW

**Comment by adriaan-telcred** [comment]
Installing sbt from Debian repo worked for me, but when I run "sbt" in my local nordpol repo it just hangs, as described here: stackoverflow.com/questions/29599309/stuck-at-getting-org-scala-sbt-sbt-0-13-6-when-running-sbt-in-terminal

I will let it run the prescribed 5-10 minutes and see what happens. Anyway, this issue should be addressed in the readme...

**Comment by adriaan-telcred** [comment]
@petter-fidesmo Eventually sbt downloaded from this repo: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.8/jars/sbt.jar

**Comment by petter-fidesmo** [comment]
@adriaan-telcred Must be some network issue. Are you behind a proxy or similar? I have had the problems with SBT hanging when I'm on 3g connection sometimes. I'll see if there are some resource that can be linked to the description that handles this problem.

**Comment by adriaan-telcred** [comment]
@petter-fidesmo As far as I can tell from the discussions I linked, it has to do with the default repo not being resolved, and after a timeout (5-10min) the fallback repo is used successfully.

We are on 3g but I never have problems downloading from maven central, etc.

**Comment by petter-fidesmo** [comment]
@adriaan-telcred Oki, I also googled around a bit and there seems to be some generic problems with ivy hanging on getting dependencies when there are small network issues (like going through an HTTP proxy). I'll leave a note regarding this in the README. Thanks for the feedback!

**Pull request merged**
