### PR TITLE
Add links to auto generated Java docs

### PR DESCRIPTION
**Pull request by petter-fidesmo**

### CODE REVIEW

**Comment by petter-fidesmo** [comment]
@Franzaine Finally the Java Docs are generated. What do you think?

**Comment by Franzaine** [comment]
@petter-fidesmo Finally indeed! It is a big improvement but I think that we should strive to document more in the future. Some of the classes and features are well documented (ex: APDU)
while others are "not at all" (ex: AndroidCard).

**Comment by Franzaine** [comment]
@petter-fidesmo what does BuildConfig do in the Android part?

**Comment by petter-fidesmo** [comment]
@Franzaine Oh. Didn't see that one. It must be one of the automatically generated files generated by the Android SDK. I guess we should try to remove it in some further release.

**Comment by Franzaine** [comment]
:+1:

**Pull request merged**
