### PR TITLE
Add TagArbiter class

### PR DESCRIPTION
**Pull request by petter-fidesmo**
- Can be used to manage tags in between activities and fragments

### CODE REVIEW

**Comment by petter-fidesmo** [comment]
@slomo What do you think of this?

**Comment by slomo** [comment]
:+1: Shouldn't also a Singelton Factory be provided?

**Comment by petter-fidesmo** [comment]
We are using android annotations to produce a singleton bean. Other than that there are two different ways to make singletons in Android, either the usual way with the factory or using the Application class. Reading about Application in Google's docs it seems that they also encourage the use of normal singletons:

*There is normally no need to subclass Application. In most situation, static singletons can provide the same functionality in a more modular way. If your singleton needs a global context (for example to register broadcast receivers), the function to retrieve it can be given a Context which internally uses Context.getApplicationContext() when first constructing the singleton.*

So I will add a normal singleton factory.

**Comment by petter-fidesmo** [comment]
@slomo Added a singletong factory and used it in the Fidesmo App. Seems to work as well as the AA one. What do you think?

**Comment by slomo** [comment]
:+1:

**Pull request merged**
