### PR TITLE
Attempt to detect and discard misbehaving devices

### PR DESCRIPTION
**Pull request by petter-fidesmo**
- Try to detect failing ISO compatible devices by sending a SELECT
  command
- If failing, discard the tag rather than dispatching it

### CODE REVIEW

**Comment by petter-fidesmo** [comment]
@slomo What do you think? It is helping on the S6, maybe not as well as the foregroundDispatch NDEF check made by Android, but it filters out some false positives when I use it with the Yubikey.

**Comment by petter-fidesmo** [comment]
One option would be to add more conversation here, but it's hard to know what more we could do that will be supported on all ISO devices.

**Comment by slomo** [comment]
Well you could check for Ndef of course ;)

**Comment by petter-fidesmo** [comment]
@slomo But I guess that would on most devices that don't have an NDEF applet just involve the select that fails.

**Comment by petter-fidesmo** [comment]
But yeah, it would be as good as the google NDEF check.

**Comment by slomo** [comment]
:+1:

**Pull request merged**
