### PR TITLE
Add APDU utilities

### PR DESCRIPTION
**Pull request by petter-fidesmo**
- Add functions to work with hex strings
- Add functions to generate SELECT APDUs

### CODE REVIEW

**Comment by petter-fidesmo** [comment]
@Franzaine What do you think about these additions?

**Comment by petter-fidesmo** [comment]
@miguelcardo Ready for review!

**Comment by miguelcardo** [comment]
@petter-fidesmo :+1: 
I think adding the `encodeHex` and `decodeHex` functions is a good idea. SELECT is maybe not so useful but anyway it is mandatory if you want to do anything with a card.

**Comment by adriaan-telcred** [comment]
Looks good to me :)

**Comment by petter-fidesmo** [comment]
Yes, I wanted to keep it minimal, since most communications will be specific to a given use case, but as you say, SELECT is always needed so thought it made sense to add it.

Since we seem to be in agreement that these functions are useful, I'll merge.

**Pull request merged**
